version: '3.1'

services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=param_changes
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  web-server:
    build:
      context: "."
    depends_on:
      - db