default_config = {
    "INFLATION_RATE": 0.43,
    "INSURANCE_FEE_FROM_SALARY": 0.30,
    "SIMULATION_YEARS": 30,
    "EMPLOYED_AND_INSURED_RATE": 0.6 * 0.37,
    # Retirment strategies
    "RETIREMENTMENT_AGE": 30,
    "BASIC_RETIRMENT_STRATEGY": True,
    # SURVIVOR
    "PROPOSED_SURVIVOR_STRATEGY": False,
    "DEATH_TO_SURVIVOR_RATE": 0.2,
    "SURVIVOR_FINAL_YEAR_OF_PAYROOL": 10,
}
